"use strict";
const request = require('request-promise');
var passport = require('passport');
var session = require('express-session')
const userAgent = "DJ-Mood-Student-Project-DEVBOOTCAMP-(https://github.com/jordanyryan/DJ-Mood)-tomchang93@gmail.com";
var User = require("./models/user");

let getRandomSubarray = function(arr, size) {
  var shuffled = arr.slice(0), i = arr.length, min = i - size, temp, index;
  while (i-- > min) {
    index = Math.floor((i + 1) * Math.random());
    temp = shuffled[index];
    shuffled[index] = shuffled[i];
    shuffled[i] = temp;
  }
  return shuffled.slice(min);
}

let getTracks = function(req, callback){


  request({
    // needs to switch the tag out with the mood
    url: `http://ws.audioscrobbler.com/2.0/?method=tag.gettoptracks&tag=${ req[0] }&api_key=${process.env.LASTFMKEY}&format=json&limit=200`,
    headers: {
      'User-Agent': userAgent
    },
    json: true
  })
  .then(function(json){

    let tracks = json["tracks"]["track"];

    let randomTracks = getRandomSubarray(tracks, 25);

    callback(randomTracks);
  })
  .catch(function(error){

    callback(null);
  })
};

let getIds = function(tracks, req, callback){

  let trackUri = []
  let j = 0;


  tracks.forEach( (track) => {
    let title = track["name"];
    let titleJoined = track["name"].split(" ").join("+");
    let artist = track["artist"]["name"];
    request({
      url: ("https://api.spotify.com/v1/search?q=" + titleJoined + "&type=track"),
      json: true
    }).then(function(json){
      let result = null
      let results = json["tracks"]["items"];
      j++
      // console.log(results, j);
      for (var i = 0; i < results.length; i++ ){
        let compArtist = results[i]["artists"].map((artist) => {
          return artist["name"];
        });
        let compTitle = results[i]["name"];
        if ( (compTitle == title) && (compArtist.includes(artist)) ){
          result = results[i]["uri"];
          trackUri.push(result)
          break;
        };
      };

      if(j === tracks.length){


        callback(trackUri);
      }
    })
    .catch(function(error){

    })
      
  })
  // while(array.length === 0){
    
  // }
};

// let getUsername = function(trackUri, request, callback){


//   request({
//     url: 'https://api.spotify.com/v1/me',
//     headers: {
//       // needs a proper authorization token
//       "Authorization": 'Bearer ' + request[1].user.accessToken,
//       'Content-Type': 'application/json'
//     }
//   }).then(function(json){
//     let username = JSON.parse(json).id

//     callback(username);
//   })
// }

let createPlaylist = function(req, trackUri , callback){
  request({
    method: 'POST',
    // needs to switch out hard coded username
    url: `https://api.spotify.com/v1/users/${req[1].user.username}/playlists`,
    body: JSON.stringify({
      "description": "A playlist generated by DJ Mood",
      "public": true,
      "name": "Bye Mauricio"
    }),
    headers: {
      // needs a proper authorization token
      "Authorization": 'Bearer ' + req[1].user.accessToken,
      'Content-Type': 'application/json'
    },
    scope: 'playlist-modify-public'
  },
  function(error, response, body){
    console.log(body);
    let playlist = JSON.parse(body).id
    callback(playlist)
  });
};

let addTracks = function(req, tracks, playlist, callback){
  let songsUrl = tracks.join(',');
  request({
    method: 'POST',
    // switch out username
    url: (`https://api.spotify.com/v1/users/${req[1].user.username}/playlists/` + playlist + '/tracks?position=0&uris=' + songsUrl),
    headers: {
      // needs a proper authorization token
      "Authorization": 'Bearer ' + req[1].user.accessToken,
      'Content-Type': 'application/json'
    }
  }).then(function(json){
    console.log("finished")
  })
}

let runner = function( req ){
  getTracks( req, function( tracks ){
    console.log("got track")
    getIds(tracks, req, function(trackUri){
      // console.log("got track uri")sp

      createPlaylist( req, trackUri, function( playlist ){
        console.log("got playlist")
        addTracks(req, trackUri,  playlist, function(){
          })
        })

    });
  })
}

module.exports = {
  getRandomSubarray,
  getTracks,
  getIds,
  createPlaylist,
  addTracks,
  runner
};